langauge: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5-dev"
  - "3.6"
  - "3.6-dev"
  - "3.7-dev"

install:
  - pip install -r requirements.txt

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

script:
  - pytest
